version: 1
runners:
  Compute:
    config-id: 1
images:
  NodeImage:
    image: node:18
    auth:
      username: << env.NPM_REGISTRY_USERNAME >>
      password: << env.NPM_REGISTRY_PASSWORD >>
jobs:
  BuildAndDeploy:
    runner: Compute
    image: NodeImage
    steps:
      - npm install -g zcatalyst-cli
      - rm -rf node_modules package-lock.json
      - npm install
      - npm run build
      - cp client-package.json dist/
      - >-
        catalyst deploy --project << env.PROJECT_NAME
        >> --org << env.CATALYST_ORG >> --token << env.CATALYST_TOKEN >>

stages:
  - name: ReactDeployment
    image: NodeImage
    jobs:
      - BuildAndDeploy
